<a href="https://colab.research.google.com/github/A11rastogi/Python-Programming/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# Numpy:
# Contains homogeneous data type
# Stores elements in sequence so provides output fast

In [ ]:
a = [1,2,3,4,5]
arr = np.array(a)
arr, type(a), type(arr)
arr**2 # here we are squaring the variables mentioned in the list a

array([ 1,  4,  9, 16, 25])

In [ ]:
arr1 = np.array(range(50))
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
# attributes
arr1.ndim # ndim provides dimension of array. here there is one dimension array starting from [0 till 49]

1

In [ ]:
# attributes
arr1.shape # provide count of elements

(50,)

In [ ]:
arr2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
mat = np.array(arr2)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mat.ndim # here provides 2 as a outcome which signifies its a 2D array >>>> x & y

2

In [ ]:
mat.shape # shows three elements in each row

(3, 3)

In [ ]:
# arange Function
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
arr4 = np.arange(1,9,2)
arr4

array([1, 3, 5, 7])

In [ ]:
np.arange(1,9,0.5)  - # Adding float value will give result in floating numbers

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5])

In [ ]:
arr5 = np.array(["Abhinav", 1,23,2.3]) # adding string in the list will convert remaining values into string
arr5

array(['Abhinav', '1', '23', '2.3'], dtype='<U32')

In [ ]:
np.array([1,2,3,4], dtype="float") # converting integer datatype into float

array([1., 2., 3., 4.])

In [ ]:
arr = np.arange(10,50,10)
arr

array([10, 20, 30, 40])

In [ ]:
arr = arr.astype('float')  # converting integer datatype into float through astype function
arr

array([10., 20., 30., 40.])

In [ ]:
# Indexing & Slicing
m1 = np.arange(1,8)
m1

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
m1[0]

1

In [ ]:
m1[3]

4

In [ ]:
m1.sum()


28

In [ ]:
np.sum(m1)

28

In [ ]:
# Fancy Indexing - Boolean Indexing
m1
m1<5 # It compares the number and populates the result in form of boolean

array([ True,  True,  True,  True, False, False, False])

In [ ]:
# Extract odd numbers
m1
m1[m1%2!=0]

array([1, 3, 5, 7])

In [ ]:
# Airbnb - Case Study
# NPS --- Net Promoter Score >>>> (%Promoters - % Detractors)
# People who give Rating btw 0-6  ----  Detractors
# People who give Rating above 8  ----- Promoters

In [ ]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK   # command to download a file

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 11.2MB/s]


In [ ]:
# loading file in a variable by keeping datatype int
scores = np.loadtxt('survey.txt', dtype = 'int')
scores

array([ 7, 10,  5, ...,  5,  9, 10])

In [ ]:
scores.shape # no of elements

(1167,)

In [ ]:
total = scores.size
total

1167

In [ ]:
scores.shape[0] # first element from list of elements

1167

In [ ]:
scores.min()
scores.max()

10

In [ ]:
promoters = scores[scores>8].size
promoters

609

In [ ]:
promoters_percent = promoters/total * 100
promoters_percent

52.185089974293064

In [ ]:
detractors = scores[scores<6].size
detractors

332

In [ ]:
detractors_percent = detractors/total * 100
detractors_percent

28.449014567266495

In [ ]:
NPS = promoters_percent - detractors_percent
round(NPS, 2)

23.74

In [ ]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(a[2:5])

[2 3 4]


In [ ]:
import numpy as np

In [ ]:
arr4 = np.arange(1,9,2)
arr4

array([1, 3, 5, 7])

In [ ]:
arr5 = np.linspace(1,9,2)
arr5

array([1., 9.])

In [1]:
import numpy as np

In [5]:
a = np.arange(5)
a
print(np.sum(a))
print(np.size(a))

10
5


In [ ]:
a = np.arange(10,22).reshape((3, 4))  # Reshaping the array into matrix of (3,4)

print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [12]:
import numpy as np
# Unique values in array using numpy
arr2 = np.array([5,4,3,5,4,6,7])
arr2
np.unique(arr2) # unique function
# count of unique values in the array
arr3 = np.unique(arr2, return_counts = True)
arr3
# compute mean
np.round(np.mean(arr2),2)

4.86

In [13]:
m = np.array(['sad', 'sad', 'happy', 'neutral',  'happy'])
m

array(['sad', 'sad', 'happy', 'neutral', 'happy'], dtype='<U7')

In [14]:
# Boolean - comparison operator
m == "sad"

array([ True,  True, False, False, False])

In [15]:
s = np.array([1400, 1500, 2500, 1800, 2400])
s

array([1400, 1500, 2500, 1800, 2400])

In [16]:
# if we want to check how many steps taken by a person who is sad
s [m == "sad"]

array([1400, 1500])

In [17]:
# 2D Array >> Sum
m = np.arange(2,14).reshape(3,4)
m

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [18]:
# Axis = 0 >> provides column wise sum
np.sum(m, axis=0)

array([18, 21, 24, 27])

In [20]:
# Axis = 1 >> provides row wise sum
np.sum(m, axis=1)

array([14, 30, 46])

In [24]:
# Any and all function
a = np.array([1,5,4,5])
b = np.array([2,3,5,7])
a>b

array([False,  True, False, False])

In [25]:
np.any(a>b)
# It does element wise comparison and draw the output >> If found any true result then throws the output as "True"

True

In [26]:
np.all(a>b)
# It does element wise comparison and draw the output >> If found any false result then throws the output as "False"

False

In [27]:
# Assigning values
arr = np.array([2,-1,5,-9,5,6,-10,3,5,-16])
arr

array([  2,  -1,   5,  -9,   5,   6, -10,   3,   5, -16])

In [28]:
arr[arr>0]
# here we have just extracted the values which are greater than "0"

array([2, 5, 5, 6, 3, 5])

In [30]:
arr[arr<0] = 1
arr
# here replaces all values which are less than "0" with "1"

array([2, 1, 5, 1, 5, 6, 1, 3, 5, 1])

In [32]:
arr[:2] = 0
arr
# replacing values present at index 0 & 1 with 0

array([0, 0, 5, 1, 5, 6, 1, 3, 5, 1])

In [38]:
# Transpose
a = np.array([[6, 28], [8, 56], [7, 19]])

x=np.transpose(a).reshape(1,6)

print(x)

[[ 6  8  7 28 56 19]]


In [37]:
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])

array = a.transpose()
array[-2,-2] # fetch the element which is present at the [-2,-2] index

56

In [41]:
# All the elements except those at the border are equated to zero.
x = np.ones((5,5))
x
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
# swapper - swapped the rows btw each other. Here, swapped first with second row?
print(A[[1,0,2], :])

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [45]:
A = np.arange(9).reshape(3,3)
print(A[:, ::-1])
# ":" >> represent rows
# "::-1" >>> reverse the columns

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [46]:
# Assignment Question
marks = np.array([85, 18, 2, 57, 65, 44])
marks

array([85, 18,  2, 57, 65, 44])

In [48]:
mask = marks>40
mask

array([ True, False, False,  True,  True,  True])

In [51]:
filtered_array = marks [mask == True]
filtered_array

array([85, 57, 65, 44])

In [ ]:
# First greater element
# Approach 1. We will firstly create a boolean array after comparing the elements of arr with target. Then we will pass this boolean array to argwhere() function which will then return a 2d array consisting of all the indices where the comparison condition is True.
# Approach 2. We can do the same steps as above with np.where with an extra step of taking care of dimensions of returned index.

In [112]:
arr = np.array([-1,2,3,4,5])
arr

array([-1,  2,  3,  4,  5])

In [113]:
target = 3
arm = (arr>target)
arm

array([False, False, False,  True,  True])

In [114]:
arn = np.argwhere(arm)
arn

array([[3],
       [4]])

In [116]:
arr = np.array([-1,2,3,4,5])
target = 6

In [117]:
arm = (arr>target)
arm

array([False, False, False, False, False])

In [118]:
arn = np.argwhere(arm)
arn

array([], shape=(0, 1), dtype=int64)

In [61]:
# One for All
m = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
K = 3

In [64]:
m = m[m%2==0]
m

array([0, 2, 4, 6, 8])

In [68]:
np.all (m > K)

False

In [76]:
# Rotate the array
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
array = mat.transpose()
array


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [80]:
print(array[:, ::-1])

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [82]:
arr1 = np.array([[ 0,  1,  2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19]])
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [93]:
row_array = arr1[1:4]
row_array

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
cols_array = row_array[:,1:]
cols_array

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [96]:
result = cols_array[::-1, :]
result

array([[13, 14, 15],
       [ 9, 10, 11],
       [ 5,  6,  7]])

In [102]:
mn = np.identity(3)
mn

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [108]:
K = 300
ans = mn * K
ans

array([[300.,   0.,   0.],
       [  0., 300.,   0.],
       [  0.,   0., 300.]])

In [109]:
ans1 = np.multiply(mn, K).astype(int)
ans1

array([[300,   0,   0],
       [  0, 300,   0],
       [  0,   0, 300]])

In [ ]:
 # Extract sub array
 https://www.scaler.com/academy/mentee-dashboard/class/88498/homework/problems/26836?navref=cl_tt_nv