<a href="https://colab.research.google.com/github/A11rastogi/Python-Programming/blob/main/NumPy_Revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [9]:
# One Dimension Array
a = [1,2,3,4,5]
arr1 = np.array(a)
arr1

array([1, 2, 3, 4, 5])

In [10]:
arr1.shape # Provides details of elements contain in array

(5,)

In [12]:
arr1.ndim # Provides dimension detail

1

In [4]:
# Two Dimension Array
b = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(b)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Two Dimension Array - here we have directly pass 2D frame in array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr.shape # three elements in each row


(3, 3)

In [11]:
arr.ndim # two dimension array

2

In [ ]:
# NumPy Built in functions

In [14]:
# np.zeros
arr3 = np.zeros(5) # for one dimension array
arr3

array([0., 0., 0., 0., 0.])

In [15]:
arr3 = np.zeros((3,3))  # for two dimension array
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# np.ones
arr4 = np.ones(5) # for one dimension array
arr4

array([1., 1., 1., 1., 1.])

In [18]:
arr4 = np.ones((3,3))  # for two dimension array
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#np.eye - It works in the diagnol array and mark the value "1" diagnolly
arrs = np.eye(3,3)
arrs

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Here its a (3,4) matrix. therefore in the fourth column "1" is not added
arrs = np.eye(3,4)
arrs

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [24]:
# np.diag - It adds value diagnolly
# Here we need to mention number in the list
ard = np.diag([1,5,9,12])
ard

array([[ 1,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 12]])

In [26]:
# np.randint - Populate any random number btw a given range
amn = np.random.randint(1,10,4)
amn

array([1, 1, 4, 1])

In [31]:
a = np.arange(11,20)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [32]:
np.sum(a)

135

In [36]:
# Reshapping one dimension array into two dimension
a = a.reshape(3,3)
a

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
# Indexing & Slicing

In [27]:
m1 = np.arange(1,8)
m1

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
m1[5]

6

In [29]:
m1[:3]

array([1, 2, 3])

In [30]:
m1[-1]

7

In [4]:
ard = np.array([[1,2,3],[4,5,6],[7,8,9]])
ard

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
ard[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [6]:
ard[1:,2:]

array([[6],
       [9]])

In [ ]:
# 3D matrix
the first index, i, selects the matrix
the second index, j, selects the row
the third index, K, selects the column

In [7]:
arrk = np.array([[[0, 1],
             [2, 3]],

            [[4, 5],
             [6, 7]]])

In [9]:
arrk[:, 0:,:1]
":" all matrix
"0:" all rows
":1" all columns

array([[[0],
        [2]],

       [[4],
        [6]]])

In [10]:
arrp = np.array([[[ 0, 1, 2],
        [ 3, 4, 5],
        [ 6, 7, 8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [11]:
arrp[1, :, :]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [27]:
arrf = np.array([2,4,6,8,10])
c=arrf.copy()
arrf[0] = 12
c
# In this section, a new NumPy array arr is created once again.
# The copy() method is used to create a new array c2.
# The statement arr[0] = 12 modifies the first element of arr, but since c2 is a separate copy with its own data, the change does not affect c2.

array([ 2,  4,  6,  8, 10])

In [22]:
arr = np.array([2, 4, 6, 8, 10])
c1 = arr.view()
arr[0] = 12
c1
# In this section, a new NumPy array arr is created with the same elements as before.
# The view() method is used to create a new array cl that shares the data of arr but has a different view.
# The statement arr[0] = 12 modifies the first element of arr.
# Since c1 and arr share the same data, the change is also reflected in c1.

array([12,  4,  6,  8, 10])

In [26]:
arr = np.array([2, 4, 6, 8, 10])
c0 = arr
c0[0] = 12
arr
# In this section, a NumPy array arr is created with the elements [2, 4, 6, 8, 10].
# The variable c0 is assigned to arr, essentially creating another reference to the same array.
# The statement c0[0] = 12 modifies the first element of arr (and c0) to 12.
# Since c0 and arr refer to the same underlying array, the change is reflected in both variables.

array([12,  4,  6,  8, 10])

In [3]:
import numpy as np


In [ ]:
# Shallow copy and Deep copy concept

In [4]:
arr = np.array([1,2,3,0,-2,4])

In [6]:
arr1 = arr*1
arr1

array([ 1,  2,  3,  0, -2,  4])

In [8]:
arr1[0] = 54
arr1

array([54,  2,  3,  0, -2,  4])

In [9]:
arr

array([ 1,  2,  3,  0, -2,  4])

In [11]:
arr1 = arr[:]
arr1

array([ 1,  2,  3,  0, -2,  4])

In [13]:
arr1[0] = 55
arr1

array([55,  2,  3,  0, -2,  4])

In [14]:
arr

array([55,  2,  3,  0, -2,  4])

In [21]:
arr10 = np.array([1,2,3,0,-2,4])

In [24]:
arr17 = arr10.reshape(2,3)
arr17

array([[ 1,  2,  3],
       [ 0, -2,  4]])

In [25]:
arr17[0][0] = 56

In [26]:
arr17

array([[56,  2,  3],
       [ 0, -2,  4]])

In [27]:
arr10

array([56,  2,  3,  0, -2,  4])

In [29]:
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.hsplit(arr,[1])

[array([0]), array([1, 2, 3, 4, 5, 6, 7, 8, 9])]

In [30]:
print(np.split(arr, 4))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [32]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.split(arr, [2,5])

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [36]:
np.split(arr, [5, 12])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([], dtype=int64)]