<a href="https://colab.research.google.com/github/A11rastogi/Python-Programming/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# Numpy:
# Contains homogeneous data type
# Stores elements in sequence so provides output fast

In [ ]:
a = [1,2,3,4,5]
arr = np.array(a)
arr, type(a), type(arr)
arr**2 # here we are squaring the variables mentioned in the list a

array([ 1,  4,  9, 16, 25])

In [ ]:
arr1 = np.array(range(50))
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
# attributes
arr1.ndim # ndim provides dimension of array. here there is one dimension array starting from [0 till 49]

1

In [ ]:
# attributes
arr1.shape # provide count of elements

(50,)

In [ ]:
arr2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
mat = np.array(arr2)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
mat.ndim # here provides 2 as a outcome which signifies its a 2D array >>>> x & y

2

In [ ]:
mat.shape # shows three elements in each row

(3, 3)

In [ ]:
# arange Function
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
arr4 = np.arange(1,9,2)
arr4

array([1, 3, 5, 7])

In [ ]:
np.arange(1,9,0.5)  - # Adding float value will give result in floating numbers

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5])

In [ ]:
arr5 = np.array(["Abhinav", 1,23,2.3]) # adding string in the list will convert remaining values into string
arr5

array(['Abhinav', '1', '23', '2.3'], dtype='<U32')

In [ ]:
np.array([1,2,3,4], dtype="float") # converting integer datatype into float

array([1., 2., 3., 4.])

In [ ]:
arr = np.arange(10,50,10)
arr

array([10, 20, 30, 40])

In [ ]:
arr = arr.astype('float')  # converting integer datatype into float through astype function
arr

array([10., 20., 30., 40.])

In [ ]:
# Indexing & Slicing
m1 = np.arange(1,8)
m1

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
m1[0]

1

In [ ]:
m1[3]

4

In [ ]:
m1.sum()


28

In [ ]:
np.sum(m1)

28

In [ ]:
# Fancy Indexing - Boolean Indexing
m1
m1<5 # It compares the number and populates the result in form of boolean

array([ True,  True,  True,  True, False, False, False])

In [ ]:
# Extract odd numbers
m1
m1[m1%2!=0]

array([1, 3, 5, 7])

In [ ]:
# Airbnb - Case Study
# NPS --- Net Promoter Score >>>> (%Promoters - % Detractors)
# People who give Rating btw 0-6  ----  Detractors
# People who give Rating above 8  ----- Promoters

In [ ]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK   # command to download a file

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 11.2MB/s]


In [ ]:
# loading file in a variable by keeping datatype int
scores = np.loadtxt('survey.txt', dtype = 'int')
scores

array([ 7, 10,  5, ...,  5,  9, 10])

In [ ]:
scores.shape # no of elements

(1167,)

In [ ]:
total = scores.size
total

1167

In [ ]:
scores.shape[0] # first element from list of elements

1167

In [ ]:
scores.min()
scores.max()

10

In [ ]:
promoters = scores[scores>8].size
promoters

609

In [ ]:
promoters_percent = promoters/total * 100
promoters_percent

52.185089974293064

In [ ]:
detractors = scores[scores<6].size
detractors

332

In [ ]:
detractors_percent = detractors/total * 100
detractors_percent

28.449014567266495

In [ ]:
NPS = promoters_percent - detractors_percent
round(NPS, 2)

23.74

In [ ]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(a[2:5])

[2 3 4]


In [ ]:
import numpy as np

In [ ]:
arr4 = np.arange(1,9,2)
arr4

array([1, 3, 5, 7])

In [ ]:
arr5 = np.linspace(1,9,2)
arr5

array([1., 9.])

In [17]:
import numpy as np

In [18]:
a = np.arange(10,22).reshape((3, 4))

print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [21]:
a = np.array([[6, 28], [8, 56], [7, 19]])

x=np.transpose(a).reshape(1,6)

print(x)

[[ 6  8  7 28 56 19]]
