<a href="https://colab.research.google.com/github/A11rastogi/Python-Programming/blob/main/Numpy_2_fitbituser_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Fitbit

In [ ]:
!gdown https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 15.2MB/s]


In [ ]:
data = np.loadtxt('fit.txt', dtype='str')

In [ ]:
data.shape

(96, 6)

In [ ]:
data.ndim

2

In [ ]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [ ]:
data[9]

array(['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'], dtype='<U10')

In [ ]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [ ]:
len(data)

96

In [ ]:
# 96*6
data.size

576

In [ ]:
data[:, 1]

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [ ]:
data_t = data.T
data_t

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [ ]:
data_t.shape

(6, 96)

In [ ]:
data_t[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [ ]:
date, step_count, mood, calories_burned, sleep_hour, activity_status = data_t

In [ ]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [ ]:
# np.array(step_count, dtype='int')

In [ ]:
step_count = step_count.astype('int')
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [ ]:
calories_burned = calories_burned.astype('int')
calories_burned

array([181, 197,   0, 174, 223, 149, 140,  38,   1,  40, 101, 152, 150,
       113,  49,  86,   6,  99, 143, 125, 129,   6,   9,  10,  72, 150,
       141, 156,  57,  72,  17, 181, 197, 131, 154, 137, 193,  19, 101,
       139, 164, 137,  22,  17,   9, 145, 192, 146, 234, 167,  16,  17,
        32,  35, 220, 116,  23,  44, 131,  86, 194,  60, 121,  76,  93,
        53,  25, 227, 125, 243,  14,  39,  55, 158,   7, 213, 116, 129,
        21,  28,  16, 180, 138, 176,  99,   5,   1,  10,  47,  84,  23,
         4,   0,   0,   0,   0])

In [ ]:
sleep_hour = sleep_hour.astype(int)
sleep_hour

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

In [ ]:
# unique values
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [ ]:
# unique values
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [ ]:
np.unique(mood, return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([40, 27, 29]))

In [ ]:
step_count[mood=='Happy']

array([4732,  330, 4550, 4435, 4779, 1831, 2255,  539, 5464, 4068, 4683,
       4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  269, 4275, 5999,
       4421, 6930, 5195,  546,  493,  995, 3608,  774, 1421, 4064, 2725,
       5934, 1867, 7422, 5537, 5376,  153, 2203])

In [ ]:
step_count[mood=='Happy'].mean()

3392.725

In [ ]:
np.mean(step_count[mood=='Happy'])

3392.725

In [ ]:
np.mean(step_count[mood=='Sad'])

2103.0689655172414

Correlation -> walking and happy.

Purpose?



In [ ]:
np.unique( mood[step_count > 4000] , return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([22,  9,  7]))

In [ ]:
np.unique( mood[step_count < 2000] , return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'), array([13,  8, 18]))

# Numpy Learning

In [ ]:
import numpy as np
a = np.arange(5)

print(np.sum(a))
print(np.size(a))   ### a.size

10
5


## Working with 2D arrays

In [ ]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a.shape

(16,)

In [ ]:
a.ndim

1

In [ ]:
a = a.reshape(8, 2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a = a.reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a.reshape(4, 5)

ValueError: ignored

In [ ]:
a.reshape(3, 4)

ValueError: ignored

In [ ]:
a.reshape(2, -1)  # converting into matrix of 2 * 8

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [ ]:
a.reshape(3, -1)

ValueError: ignored

In [ ]:
a.reshape(-1, -1)

ValueError: ignored

In [ ]:
a = a.reshape(1, -1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(1, 16)

In [ ]:
a.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [ ]:
a.reshape(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
# array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
a = a.reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
len(a)

4

In [ ]:
a[0][2]

2

In [ ]:
a[2][2]

10

In [ ]:
a[2,2]

10

In [ ]:
a[-1,-1]

15

In [ ]:
a[-2, -3]

9

In [ ]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.shape

(3, 4)

In [ ]:
a = a.T
a

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a.shape

(4, 3)

In [ ]:
my_list = [1, 2, 3, 4, 5]
my_list.extend([6])


In [ ]:
my_list

[1, 2, 3, 4, 5, 6]

In [ ]:
a

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a[[0,1,3]]

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 3,  7, 11]])

In [ ]:
a[[0,1]]

array([[0, 4, 8],
       [1, 5, 9]])

In [ ]:
a[0,1]

4

In [ ]:
m1 = np.arange(5,17)
m1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
m1[[0,5,5,0]]

array([ 5, 10, 10,  5])

## Array(2D) Slicing

In [ ]:
m1 = np.arange(2, 14).reshape(3, 4)
m1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
m1[:2]

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [ ]:
# m1[ rows , cols]

In [ ]:
m1[ : , 1] # Here ":" signifies all the rows and "1" represent first column.
# Output we are getting in a row as showing it in a form of 1D array

array([ 3,  7, 11])

In [ ]:
m1[ : , :2]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [ ]:
m1 = np.arange(5, 25).reshape(5, 4)
m1

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
m1[ 1:3  , :3]

array([[ 9, 10, 11],
       [13, 14, 15]])

In [ ]:
m1[ 1:4 ,  1:]

array([[10, 11, 12],
       [14, 15, 16],
       [18, 19, 20]])

In [ ]:
m1[ 3: , 2: ]

array([[19, 20],
       [23, 24]])

In [ ]:
m1[ -2: , -2: ]

array([[19, 20],
       [23, 24]])

In [ ]:
m1 = np.arange(12).reshape(3, 4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
m1 < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
m1[m1<6]

array([0, 1, 2, 3, 4, 5])

In [ ]:
m = np.array(['sad', 'sad', 'happy', 'neutral',  'happy'])
m

array(['sad', 'sad', 'happy', 'neutral', 'happy'], dtype='<U7')

In [ ]:
m == 'happy'

array([False, False,  True, False,  True])

In [ ]:
s = np.array([1400, 1500, 2500, 1800, 2400])
s

array([1400, 1500, 2500, 1800, 2400])

In [ ]:
s[m == 'happy']

array([2500, 2400])

In [ ]:
a = np.arange(1, 11)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.sum(a)

55

In [ ]:
a.sum()

55

In [ ]:
np.mean(a)

5.5

In [ ]:
a.mean()

5.5

In [ ]:
a = np.arange(2, 14).reshape(3, 4)
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
a.sum()

90

In [ ]:
a.shape

(3, 4)

In [ ]:
# row wise sum.
np.sum(a, axis=1)

array([14, 30, 46])

In [ ]:
a.sum(axis=0)

array([18, 21, 24, 27])

In [ ]:
a = np.array([1,2,3,4])
b = np.array([4,2,1,3])

In [ ]:
a>b

array([False, False,  True,  True])

In [ ]:
np.any(a>b)

True

In [ ]:
np.all(a>b)

False

In [ ]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [ ]:
arr[arr>0]

array([ 4, 27, 34,  4])

In [ ]:
arr[arr<0] = -1

In [ ]:
arr

array([-1,  4, 27, 34, -1,  0, -1, -1,  4,  0])

In [ ]:
arr[:2] = 0

In [ ]:
arr

array([ 0,  0, 27, 34, -1,  0, -1, -1,  4,  0])

In [ ]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
mask

array([ True, False,  True, False,  True, False])

In [ ]:
a = [1,2,3,4,5]
b = [8,7,6]
a[2:] = b[::-1]

a

[1, 2, 6, 7, 8]

In [ ]:
birds = np.array(['spoonbills', 'plovers1', 'plovers2', 'plovers3', 'plovers4', 'Cranes', 'plovers5', 'plovers6', 'Cranes', 'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])

In [ ]:
idx = np.argsort(age)

In [ ]:
birds[idx]

array(['plovers3', 'plovers6', 'plovers4', 'plovers2', 'plovers5',
       'Cranes', 'spoonbills', 'Cranes', 'plovers1', 'spoonbills'],
      dtype='<U10')